-- Create schema
CREATE SCHEMA IF NOT EXISTS financial_radar;

-- Balance Sheet Annual
DROP TABLE IF EXISTS financial_radar.balance_sheet_annual;
CREATE TABLE financial_radar.balance_sheet_annual (
    symbol VARCHAR,
    date DATE,
    cash_and_equivalents DOUBLE PRECISION,
    cash_and_cash_equivalents DOUBLE PRECISION,
    cash_growth DOUBLE PRECISION,
    receivables DOUBLE PRECISION,
    inventory DOUBLE PRECISION,
    other_current_assets DOUBLE PRECISION,
    total_current_assets DOUBLE PRECISION,
    property_plant_and_equipment DOUBLE PRECISION,
    goodwill_and_intangibles DOUBLE PRECISION,
    other_long_term_assets DOUBLE PRECISION,
    total_long_term_assets DOUBLE PRECISION,
    total_assets DOUBLE PRECISION,
    accounts_payable DOUBLE PRECISION,
    deferred_revenue DOUBLE PRECISION,
    other_current_liabilities DOUBLE PRECISION,
    total_current_liabilities DOUBLE PRECISION,
    other_long_term_liabilities DOUBLE PRECISION,
    total_long_term_liabilities DOUBLE PRECISION,
    total_liabilities DOUBLE PRECISION,
    common_stock DOUBLE PRECISION,
    retained_earnings DOUBLE PRECISION,
    comprehensive_income DOUBLE PRECISION,
    shareholders_equity DOUBLE PRECISION,
    total_liabilities_and_equity DOUBLE PRECISION,
    net_cash_or_debt DOUBLE PRECISION,
    net_cash_or_debt_growth DOUBLE PRECISION,
    net_cash_per_share DOUBLE PRECISION,
    working_capital DOUBLE PRECISION,
    book_value_per_share DOUBLE PRECISION,
    long_term_investments DOUBLE PRECISION,
    current_debt DOUBLE PRECISION,
    total_debt DOUBLE PRECISION,
    debt_growth DOUBLE PRECISION,
    long_term_debt DOUBLE PRECISION,
    short_term_investments DOUBLE PRECISION,
    goodwill DOUBLE PRECISION,
    intangible_assets DOUBLE PRECISION
);

-- Balance Sheet Quarterly
DROP TABLE IF EXISTS financial_radar.balance_sheet_quarterly;
CREATE TABLE financial_radar.balance_sheet_quarterly (
    symbol VARCHAR,
    date DATE,
    cash_and_equivalents DOUBLE PRECISION,
    short_term_investments DOUBLE PRECISION,
    cash_and_cash_equivalents DOUBLE PRECISION,
    cash_growth DOUBLE PRECISION,
    receivables DOUBLE PRECISION,
    inventory DOUBLE PRECISION,
    other_current_assets DOUBLE PRECISION,
    total_current_assets DOUBLE PRECISION,
    property_plant_and_equipment DOUBLE PRECISION,
    long_term_investments DOUBLE PRECISION,
    goodwill_and_intangibles DOUBLE PRECISION,
    other_long_term_assets DOUBLE PRECISION,
    total_long_term_assets DOUBLE PRECISION,
    total_assets DOUBLE PRECISION,
    accounts_payable DOUBLE PRECISION,
    deferred_revenue DOUBLE PRECISION,
    current_debt DOUBLE PRECISION,
    other_current_liabilities DOUBLE PRECISION,
    total_current_liabilities DOUBLE PRECISION,
    other_long_term_liabilities DOUBLE PRECISION,
    total_long_term_liabilities DOUBLE PRECISION,
    total_liabilities DOUBLE PRECISION,
    total_debt DOUBLE PRECISION,
    common_stock DOUBLE PRECISION,
    retained_earnings DOUBLE PRECISION,
    comprehensive_income DOUBLE PRECISION,
    shareholders_equity DOUBLE PRECISION,
    total_liabilities_and_equity DOUBLE PRECISION,
    net_cash_or_debt DOUBLE PRECISION,
    net_cash_or_debt_growth DOUBLE PRECISION,
    net_cash_per_share DOUBLE PRECISION,
    working_capital DOUBLE PRECISION,
    book_value_per_share DOUBLE PRECISION,
    debt_growth DOUBLE PRECISION,
    long_term_debt DOUBLE PRECISION,
    goodwill DOUBLE PRECISION,
    intangible_assets DOUBLE PRECISION
);

-- Cash Flow Statement Annual
DROP TABLE IF EXISTS financial_radar.cash_flow_statement_annual;
CREATE TABLE financial_radar.cash_flow_statement_annual (
    symbol VARCHAR,
    date DATE,
    net_income DOUBLE PRECISION,
    depreciation_and_amortization DOUBLE PRECISION,
    share_based_compensation DOUBLE PRECISION,
    other_operating_activities DOUBLE PRECISION,
    operating_cash_flow DOUBLE PRECISION,
    capital_expenditures DOUBLE PRECISION,
    investing_cash_flow DOUBLE PRECISION,
    share_issuance_or_repurchase DOUBLE PRECISION,
    other_financing_activities DOUBLE PRECISION,
    financing_cash_flow DOUBLE PRECISION,
    net_cash_flow DOUBLE PRECISION,
    free_cash_flow DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    free_cash_flow_per_share DOUBLE PRECISION,
    change_in_investments DOUBLE PRECISION,
    debt_issued_or_paid DOUBLE PRECISION,
    operating_cash_flow_growth DOUBLE PRECISION,
    acquisitions DOUBLE PRECISION,
    dividends_paid DOUBLE PRECISION,
    other_investing_activities DOUBLE PRECISION,
    free_cash_flow_growth DOUBLE PRECISION,
    common_stock_issued DOUBLE PRECISION,
    share_repurchases DOUBLE PRECISION
);

-- Cash Flow Statement Quarterly
DROP TABLE IF EXISTS financial_radar.cash_flow_statement_quarterly;
CREATE TABLE financial_radar.cash_flow_statement_quarterly (
    symbol VARCHAR,
    date DATE,
    net_income DOUBLE PRECISION,
    depreciation_and_amortization DOUBLE PRECISION,
    share_based_compensation DOUBLE PRECISION,
    other_operating_activities DOUBLE PRECISION,
    operating_cash_flow DOUBLE PRECISION,
    operating_cash_flow_growth DOUBLE PRECISION,
    capital_expenditures DOUBLE PRECISION,
    change_in_investments DOUBLE PRECISION,
    investing_cash_flow DOUBLE PRECISION,
    share_issuance_or_repurchase DOUBLE PRECISION,
    other_financing_activities DOUBLE PRECISION,
    financing_cash_flow DOUBLE PRECISION,
    net_cash_flow DOUBLE PRECISION,
    free_cash_flow DOUBLE PRECISION,
    free_cash_flow_growth DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    free_cash_flow_per_share DOUBLE PRECISION,
    debt_issued_or_paid DOUBLE PRECISION,
    acquisitions DOUBLE PRECISION,
    dividends_paid DOUBLE PRECISION,
    other_investing_activities DOUBLE PRECISION,
    share_repurchases DOUBLE PRECISION,
    common_stock_issued DOUBLE PRECISION
);

DROP TABLE IF EXISTS financial_radar.income_statement_annual;
CREATE TABLE financial_radar.income_statement_annual (
    symbol VARCHAR,
    date DATE,
    revenue DOUBLE PRECISION,
    revenue_growth_yoy DOUBLE PRECISION,
    cost_of_revenue DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    selling_general_and_admin DOUBLE PRECISION,
    research_and_development DOUBLE PRECISION,
    operating_expenses DOUBLE PRECISION,
    operating_income DOUBLE PRECISION,
    other_expense_or_income DOUBLE PRECISION,
    pretax_income DOUBLE PRECISION,
    income_tax DOUBLE PRECISION,
    net_income DOUBLE PRECISION,
    preferred_dividends DOUBLE PRECISION,
    net_income_common DOUBLE PRECISION,
    shares_outstanding_basic DOUBLE PRECISION,
    shares_outstanding_diluted DOUBLE PRECISION,
    shares_change DOUBLE PRECISION,
    eps_basic DOUBLE PRECISION,
    eps_diluted DOUBLE PRECISION,
    free_cash_flow_per_share DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    operating_margin DOUBLE PRECISION,
    profit_margin DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    ebitda DOUBLE PRECISION,
    ebitda_margin DOUBLE PRECISION,
    depreciation_and_amortization DOUBLE PRECISION,
    ebit DOUBLE PRECISION,
    ebit_margin DOUBLE PRECISION,
    effective_tax_rate DOUBLE PRECISION,
    interest_expense_or_income DOUBLE PRECISION,
    net_income_growth DOUBLE PRECISION,
    eps_growth DOUBLE PRECISION,
    other_operating_expenses DOUBLE PRECISION,
    dividend_per_share DOUBLE PRECISION,
    dividend_growth DOUBLE PRECISION,
    selling_and_marketing DOUBLE PRECISION,
    general_and_administrative DOUBLE PRECISION,
    interest_income DOUBLE PRECISION,
    interest_expense DOUBLE PRECISION
);

-- Income Statement Quarterly
DROP TABLE IF EXISTS financial_radar.income_statement_quarterly;
CREATE TABLE financial_radar.income_statement_quarterly (
    symbol VARCHAR,
    date DATE,
    revenue DOUBLE PRECISION,
    revenue_growth_yoy DOUBLE PRECISION,
    cost_of_revenue DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    selling_general_and_admin DOUBLE PRECISION,
    research_and_development DOUBLE PRECISION,
    operating_expenses DOUBLE PRECISION,
    operating_income DOUBLE PRECISION,
    other_expense_or_income DOUBLE PRECISION,
    pretax_income DOUBLE PRECISION,
    income_tax DOUBLE PRECISION,
    net_income DOUBLE PRECISION,
    preferred_dividends DOUBLE PRECISION,
    net_income_common DOUBLE PRECISION,
    shares_outstanding_basic DOUBLE PRECISION,
    shares_outstanding_diluted DOUBLE PRECISION,
    shares_change DOUBLE PRECISION,
    eps_basic DOUBLE PRECISION,
    eps_diluted DOUBLE PRECISION,
    free_cash_flow_per_share DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    operating_margin DOUBLE PRECISION,
    profit_margin DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    ebitda DOUBLE PRECISION,
    ebitda_margin DOUBLE PRECISION,
    depreciation_and_amortization DOUBLE PRECISION,
    ebit DOUBLE PRECISION,
    ebit_margin DOUBLE PRECISION,
    effective_tax_rate DOUBLE PRECISION,
    interest_expense_or_income DOUBLE PRECISION,
    net_income_growth DOUBLE PRECISION,
    eps_growth DOUBLE PRECISION,
    other_operating_expenses DOUBLE PRECISION,
    dividend_per_share DOUBLE PRECISION,
    dividend_growth DOUBLE PRECISION,
    selling_and_marketing DOUBLE PRECISION,
    general_and_administrative DOUBLE PRECISION,
    interest_income DOUBLE PRECISION,
    interest_expense DOUBLE PRECISION
);


--- Profile 
DROP TABLE IF EXISTS financial_radar.profile;
CREATE TABLE financial_radar.profile (
    symbol VARCHAR,
    sector VARCHAR,
    industry VARCHAR,
    website VARCHAR,
    longBusinessSummary VARCHAR(MAX),
    address1 VARCHAR,
    city VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    country VARCHAR,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    fullTimeEmployees DOUBLE PRECISION
);

--- Ratios Annual
DROP TABLE IF EXISTS financial_radar.ratios_annual;
CREATE TABLE financial_radar.ratios_annual (
    symbol VARCHAR,
    date DATE,
    market_capitalization DOUBLE PRECISION,
    market_cap_growth DOUBLE PRECISION,
    enterprise_value DOUBLE PRECISION,
    pe_ratio DOUBLE PRECISION,
    ps_ratio DOUBLE PRECISION,
    pb_ratio DOUBLE PRECISION,
    p_over_fcf_ratio DOUBLE PRECISION,
    p_over_ocf_ratio DOUBLE PRECISION,
    ev_over_sales_ratio DOUBLE PRECISION,
    ev_over_ebitda_ratio DOUBLE PRECISION,
    ev_over_ebit_ratio DOUBLE PRECISION,
    ev_over_fcf_ratio DOUBLE PRECISION,
    current_ratio DOUBLE PRECISION,
    asset_turnover DOUBLE PRECISION,
    return_on_equity_roe DOUBLE PRECISION,
    return_on_assets_roa DOUBLE PRECISION,
    return_on_capital_roic DOUBLE PRECISION,
    earnings_yield DOUBLE PRECISION,
    fcf_yield DOUBLE PRECISION,
    buyback_yield_or_dilution DOUBLE PRECISION,
    total_shareholder_return DOUBLE PRECISION,
    debt_or_equity_ratio DOUBLE PRECISION,
    debt_or_ebitda_ratio DOUBLE PRECISION,
    debt_or_fcf_ratio DOUBLE PRECISION,
    dividend_yield DOUBLE PRECISION,
    payout_ratio DOUBLE PRECISION,
    revenue DOUBLE PRECISION,
    revenue_growth_yoy DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    selling_general_and_admin DOUBLE PRECISION,
    other_operating_expenses DOUBLE PRECISION,
    operating_expenses DOUBLE PRECISION,
    operating_income DOUBLE PRECISION,
    pretax_income DOUBLE PRECISION,
    income_tax DOUBLE PRECISION,
    net_income DOUBLE PRECISION,
    preferred_dividends DOUBLE PRECISION,
    net_income_common DOUBLE PRECISION,
    net_income_growth DOUBLE PRECISION,
    shares_outstanding_basic DOUBLE PRECISION,
    shares_outstanding_diluted DOUBLE PRECISION,
    shares_change DOUBLE PRECISION,
    eps_basic DOUBLE PRECISION,
    eps_diluted DOUBLE PRECISION,
    eps_growth DOUBLE PRECISION,
    free_cash_flow_per_share DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    operating_margin DOUBLE PRECISION,
    profit_margin DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    effective_tax_rate DOUBLE PRECISION,
    ebitda DOUBLE PRECISION,
    ebitda_margin DOUBLE PRECISION,
    depreciation_and_amortization DOUBLE PRECISION,
    ebit DOUBLE PRECISION,
    ebit_margin DOUBLE PRECISION
);

-- Ratios Quarterly 
DROP TABLE IF EXISTS financial_radar.ratios_quarterly;
CREATE TABLE financial_radar.ratios_quarterly (
    symbol VARCHAR,
    date DATE,
    market_capitalization DOUBLE PRECISION,
    market_cap_growth DOUBLE PRECISION,
    enterprise_value DOUBLE PRECISION,
    pe_ratio DOUBLE PRECISION,
    ps_ratio DOUBLE PRECISION,
    pb_ratio DOUBLE PRECISION,
    debt_or_equity_ratio DOUBLE PRECISION,
    current_ratio DOUBLE PRECISION,
    buyback_yield_or_dilution DOUBLE PRECISION,
    total_shareholder_return DOUBLE PRECISION,
    dividend_yield DOUBLE PRECISION,
    payout_ratio DOUBLE PRECISION,
    asset_turnover DOUBLE PRECISION,
    return_on_equity_roe DOUBLE PRECISION,
    return_on_assets_roa DOUBLE PRECISION,
    return_on_capital_roic DOUBLE PRECISION,
    earnings_yield DOUBLE PRECISION,
    fcf_yield DOUBLE PRECISION,
    revenue DOUBLE PRECISION,
    revenue_growth_yoy DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    selling_general_and_admin DOUBLE PRECISION,
    other_operating_expenses DOUBLE PRECISION,
    operating_expenses DOUBLE PRECISION,
    operating_income DOUBLE PRECISION,
    pretax_income DOUBLE PRECISION,
    income_tax DOUBLE PRECISION,
    net_income DOUBLE PRECISION,
    preferred_dividends DOUBLE PRECISION,
    net_income_common DOUBLE PRECISION,
    net_income_growth DOUBLE PRECISION,
    shares_outstanding_basic DOUBLE PRECISION,
    shares_outstanding_diluted DOUBLE PRECISION,
    shares_change DOUBLE PRECISION,
    eps_basic DOUBLE PRECISION,
    eps_diluted DOUBLE PRECISION,
    eps_growth DOUBLE PRECISION,
    free_cash_flow_per_share DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    operating_margin DOUBLE PRECISION,
    profit_margin DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    effective_tax_rate DOUBLE PRECISION,
    ebitda DOUBLE PRECISION,
    ebitda_margin DOUBLE PRECISION,
    depreciation_and_amortization DOUBLE PRECISION,
    ebit DOUBLE PRECISION,
    ebit_margin DOUBLE PRECISION,
    ev_over_sales_ratio DOUBLE PRECISION,
    ev_over_ebitda_ratio DOUBLE PRECISION,
    ev_over_fcf_ratio DOUBLE PRECISION
);

-- Stock Prices
DROP TABLE IF EXISTS financial_radar.stock_price;
CREATE TABLE financial_radar.stock_price (
    symbol VARCHAR(255),
    date DATE,
    "open" DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    adjclose DOUBLE PRECISION,
    splits DOUBLE PRECISION,
    dividends DOUBLE PRECISION
);

